name: archchronos
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.1.29+2

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^4.0.1+3
  firebase_auth: ^0.11.1+1
  firebase_messaging: ^5.0.1+1
  firebase_core: ^0.4.0+1
  intl: ^0.15.8
  cloud_firestore: ^0.12.0
  shared_preferences: 0.5.2
  email_validator: ^1.0.0
  connectivity: ^0.4.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/user.png
    - assets/google.jpg
    - assets/google.png
    - assets/arch_a.png
    - assets/emailPDF.png
    - assets/icons8-calendar-1-50.png
    - assets/icons8-calendar-2-50.png
    - assets/icons8-calendar-3-50.png
    - assets/icons8-calendar-4-50.png
    - assets/icons8-calendar-5-50.png
    - assets/icons8-calendar-6-50.png
    - assets/icons8-calendar-7-50.png
    - assets/icons8-calendar-8-50.png
    - assets/icons8-calendar-9-50.png
    - assets/icons8-calendar-10-50.png
    - assets/icons8-calendar-11-50.png
    - assets/icons8-calendar-12-50.png
    - assets/icons8-calendar-13-50.png
    - assets/icons8-calendar-14-50.png
    - assets/icons8-calendar-15-50.png
    - assets/icons8-calendar-16-50.png
    - assets/icons8-calendar-17-50.png
    - assets/icons8-calendar-18-50.png
    - assets/icons8-calendar-19-50.png
    - assets/icons8-calendar-20-50.png
    - assets/icons8-calendar-21-50.png
    - assets/icons8-calendar-22-50.png
    - assets/icons8-calendar-23-50.png
    - assets/icons8-calendar-24-50.png
    - assets/icons8-calendar-25-50.png
    - assets/icons8-calendar-26-50.png
    - assets/icons8-calendar-27-50.png
    - assets/icons8-calendar-28-50.png
    - assets/icons8-calendar-29-50.png
    - assets/icons8-calendar-30-50.png
    - assets/icons8-calendar-31-50.png

  fonts:
    - family: Kalam
      fonts:
        - asset: fonts/Kalam-Regular.ttf